/*
* Copyright 2021 James F. Bowring and CIRDLES.org.
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*
* This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
* See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
* Any modifications to this file will be lost upon recompilation of the source schema. 
* Generated on: 2021.01.21 at 01:20:39 PM EST 
*/
package org.cirdles.squid.prawnLegacy;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.cirdles.squid.shrimp.ShrimpDataLegacyFileInterface;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="software_version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="runs" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *         &lt;element name="run" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sets" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="peaks" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="scans" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="dead_time_ns" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="sbm_zero_cps" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                   &lt;element name="autocentering" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="qt1y_mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="deflect_beam_between_peaks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="autocenter_method" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="run_table">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                             &lt;element name="trim_mass" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
 *                             &lt;element name="trim_mass_offset" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
 *                             &lt;element name="count_time_sec" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
 *                             &lt;element name="delay_sec" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
 *                             &lt;element name="collector_focus" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
 *                             &lt;element name="centering" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                             &lt;element name="centering_time_sec" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
 *                             &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                             &lt;element name="centering_frequency" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                             &lt;element name="detector" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                             &lt;element name="cup_settings" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="set">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *                             &lt;element name="qt1y" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="pbm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="data">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="peak" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="peak_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="scan" maxOccurs="unbounded">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="scan_number" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
 *                                                           &lt;element name="trim_mass" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                                           &lt;element name="time_stamp_sec" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                                                           &lt;element name="autocentering" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="ion_count" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" maxOccurs="unbounded"/>
 *                                                           &lt;element name="norm_count" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "softwareVersion",
    "runs",
    "run"
})
@XmlRootElement(name = "prawn_file")
public class PrawnLegacyFile implements ShrimpDataLegacyFileInterface, Serializable {
//    private static final long serialVersionUID = ;

    @XmlElement(name = "software_version", required = true)
    protected String softwareVersion;
    @XmlSchemaType(name = "unsignedByte")
    protected short runs;
    @XmlElement(required = true)
    protected List<PrawnLegacyFile.Run> run;

    /**
     * Gets the value of the softwareVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * Sets the value of the softwareVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwareVersion(String value) {
        this.softwareVersion = value;
    }

    /**
     * Gets the value of the runs property.
     * 
     */
    public short getRuns() {
        return runs;
    }

    /**
     * Sets the value of the runs property.
     * 
     */
    public void setRuns(short value) {
        this.runs = value;
    }

    /**
     * Gets the value of the run property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the run property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRun().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrawnFile.Run }
     * 
     * 
     */
    public List<PrawnLegacyFile.Run> getRun() {
        if (run == null) {
            run = new ArrayList<PrawnLegacyFile.Run>();
        }
        return this.run;
    }

    @Override
    public int extractCountOfRuns() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sets" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="peaks" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="scans" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="dead_time_ns" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="sbm_zero_cps" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *         &lt;element name="autocentering" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="qt1y_mode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="deflect_beam_between_peaks" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="autocenter_method" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="run_table">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                   &lt;element name="trim_mass" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
     *                   &lt;element name="trim_mass_offset" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
     *                   &lt;element name="count_time_sec" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
     *                   &lt;element name="delay_sec" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
     *                   &lt;element name="collector_focus" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
     *                   &lt;element name="centering" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                   &lt;element name="centering_time_sec" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
     *                   &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                   &lt;element name="centering_frequency" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                   &lt;element name="detector" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                   &lt;element name="cup_settings" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="set">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}time"/>
     *                   &lt;element name="qt1y" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="pbm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="data">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="peak" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="peak_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="scan" maxOccurs="unbounded">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="scan_number" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
     *                                                 &lt;element name="trim_mass" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                                                 &lt;element name="time_stamp_sec" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                                                 &lt;element name="autocentering" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="ion_count" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" maxOccurs="unbounded"/>
     *                                                 &lt;element name="norm_count" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "sets",
        "peaks",
        "scans",
        "deadTimeNs",
        "sbmZeroCps",
        "autocentering",
        "qt1YMode",
        "deflectBeamBetweenPeaks",
        "autocenterMethod",
        "runTable",
        "set"
    })
    public static class Run {

        @XmlElement(required = true)
        protected String title;
        @XmlSchemaType(name = "unsignedByte")
        protected short sets;
        @XmlSchemaType(name = "unsignedByte")
        protected short peaks;
        @XmlSchemaType(name = "unsignedByte")
        protected short scans;
        @XmlElement(name = "dead_time_ns")
        @XmlSchemaType(name = "unsignedByte")
        protected int deadTimeNs;
        @XmlElement(name = "sbm_zero_cps")
        @XmlSchemaType(name = "unsignedByte")
        protected int sbmZeroCps;
        @XmlElement(required = true)
        protected String autocentering;
        @XmlElement(name = "qt1y_mode", required = true)
        protected String qt1YMode;
        @XmlElement(name = "deflect_beam_between_peaks", required = true)
        protected String deflectBeamBetweenPeaks;
        @XmlElement(name = "autocenter_method", required = true)
        protected String autocenterMethod;
        @XmlElement(name = "run_table", required = true)
        protected PrawnLegacyFile.Run.RunTable runTable;
        @XmlElement(required = true)
        protected PrawnLegacyFile.Run.Set set;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the sets property.
         * 
         */
        public short getSets() {
            return sets;
        }

        /**
         * Sets the value of the sets property.
         * 
         */
        public void setSets(short value) {
            this.sets = value;
        }

        /**
         * Gets the value of the peaks property.
         * 
         */
        public short getPeaks() {
            return peaks;
        }

        /**
         * Sets the value of the peaks property.
         * 
         */
        public void setPeaks(short value) {
            this.peaks = value;
        }

        /**
         * Gets the value of the scans property.
         * 
         */
        public short getScans() {
            return scans;
        }

        /**
         * Sets the value of the scans property.
         * 
         */
        public void setScans(short value) {
            this.scans = value;
        }

        /**
         * Gets the value of the deadTimeNs property.
         * 
         */
        public int getDeadTimeNs() {
            return deadTimeNs;
        }

        /**
         * Sets the value of the deadTimeNs property.
         * 
         */
        public void setDeadTimeNs(int value) {
            this.deadTimeNs = value;
        }

        /**
         * Gets the value of the sbmZeroCps property.
         * 
         */
        public int getSbmZeroCps() {
            return sbmZeroCps;
        }

        /**
         * Sets the value of the sbmZeroCps property.
         * 
         */
        public void setSbmZeroCps(int value) {
            this.sbmZeroCps = value;
        }

        /**
         * Gets the value of the autocentering property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAutocentering() {
            return autocentering;
        }

        /**
         * Sets the value of the autocentering property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAutocentering(String value) {
            this.autocentering = value;
        }

        /**
         * Gets the value of the qt1YMode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQt1YMode() {
            return qt1YMode;
        }

        /**
         * Sets the value of the qt1YMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQt1YMode(String value) {
            this.qt1YMode = value;
        }

        /**
         * Gets the value of the deflectBeamBetweenPeaks property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeflectBeamBetweenPeaks() {
            return deflectBeamBetweenPeaks;
        }

        /**
         * Sets the value of the deflectBeamBetweenPeaks property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeflectBeamBetweenPeaks(String value) {
            this.deflectBeamBetweenPeaks = value;
        }

        /**
         * Gets the value of the autocenterMethod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAutocenterMethod() {
            return autocenterMethod;
        }

        /**
         * Sets the value of the autocenterMethod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAutocenterMethod(String value) {
            this.autocenterMethod = value;
        }

        /**
         * Gets the value of the runTable property.
         * 
         * @return
         *     possible object is
         *     {@link PrawnFile.Run.RunTable }
         *     
         */
        public PrawnLegacyFile.Run.RunTable getRunTable() {
            return runTable;
        }

        /**
         * Sets the value of the runTable property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrawnFile.Run.RunTable }
         *     
         */
        public void setRunTable(PrawnLegacyFile.Run.RunTable value) {
            this.runTable = value;
        }

        /**
         * Gets the value of the set property.
         * 
         * @return
         *     possible object is
         *     {@link PrawnFile.Run.Set }
         *     
         */
        public PrawnLegacyFile.Run.Set getSet() {
            return set;
        }

        /**
         * Sets the value of the set property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrawnFile.Run.Set }
         *     
         */
        public void setSet(PrawnLegacyFile.Run.Set value) {
            this.set = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *         &lt;element name="trim_mass" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
         *         &lt;element name="trim_mass_offset" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
         *         &lt;element name="count_time_sec" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
         *         &lt;element name="delay_sec" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
         *         &lt;element name="collector_focus" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
         *         &lt;element name="centering" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *         &lt;element name="centering_time_sec" type="{http://www.w3.org/2001/XMLSchema}decimal" maxOccurs="unbounded"/>
         *         &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *         &lt;element name="centering_frequency" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *         &lt;element name="detector" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *         &lt;element name="cup_settings" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "name",
            "trimMass",
            "trimMassOffset",
            "countTimeSec",
            "delaySec",
            "collectorFocus",
            "centering",
            "centeringTimeSec",
            "reference",
            "centeringFrequency",
            "detector",
            "cupSettings"
        })
        public static class RunTable {

            @XmlElement(required = true)
            protected List<String> name;
            @XmlElement(name = "trim_mass", required = true)
            protected List<BigDecimal> trimMass;
            @XmlElement(name = "trim_mass_offset", required = true)
            protected List<BigDecimal> trimMassOffset;
            @XmlElement(name = "count_time_sec", required = true)
            protected List<BigDecimal> countTimeSec;
            @XmlElement(name = "delay_sec", required = true)
            protected List<BigDecimal> delaySec;
            @XmlElement(name = "collector_focus", required = true)
            protected List<BigDecimal> collectorFocus;
            @XmlElement(required = true)
            protected List<String> centering;
            @XmlElement(name = "centering_time_sec", required = true)
            protected List<BigDecimal> centeringTimeSec;
            @XmlElement(required = true)
            protected List<String> reference;
            @XmlElement(name = "centering_frequency", required = true)
            protected List<String> centeringFrequency;
            @XmlElement(required = true)
            protected List<String> detector;
            @XmlElement(name = "cup_settings", required = true)
            protected List<String> cupSettings;

            /**
             * Gets the value of the name property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the name property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getName().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getName() {
                if (name == null) {
                    name = new ArrayList<String>();
                }
                return this.name;
            }

            /**
             * Gets the value of the trimMass property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the trimMass property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTrimMass().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BigDecimal }
             * 
             * 
             */
            public List<BigDecimal> getTrimMass() {
                if (trimMass == null) {
                    trimMass = new ArrayList<BigDecimal>();
                }
                return this.trimMass;
            }

            /**
             * Gets the value of the trimMassOffset property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the trimMassOffset property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getTrimMassOffset().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BigDecimal }
             * 
             * 
             */
            public List<BigDecimal> getTrimMassOffset() {
                if (trimMassOffset == null) {
                    trimMassOffset = new ArrayList<BigDecimal>();
                }
                return this.trimMassOffset;
            }

            /**
             * Gets the value of the countTimeSec property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the countTimeSec property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCountTimeSec().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BigDecimal }
             * 
             * 
             */
            public List<BigDecimal> getCountTimeSec() {
                if (countTimeSec == null) {
                    countTimeSec = new ArrayList<BigDecimal>();
                }
                return this.countTimeSec;
            }

            /**
             * Gets the value of the delaySec property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the delaySec property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDelaySec().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BigDecimal }
             * 
             * 
             */
            public List<BigDecimal> getDelaySec() {
                if (delaySec == null) {
                    delaySec = new ArrayList<BigDecimal>();
                }
                return this.delaySec;
            }

            /**
             * Gets the value of the collectorFocus property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the collectorFocus property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCollectorFocus().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BigDecimal }
             * 
             * 
             */
            public List<BigDecimal> getCollectorFocus() {
                if (collectorFocus == null) {
                    collectorFocus = new ArrayList<BigDecimal>();
                }
                return this.collectorFocus;
            }

            /**
             * Gets the value of the centering property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the centering property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCentering().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getCentering() {
                if (centering == null) {
                    centering = new ArrayList<String>();
                }
                return this.centering;
            }

            /**
             * Gets the value of the centeringTimeSec property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the centeringTimeSec property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCenteringTimeSec().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BigDecimal }
             * 
             * 
             */
            public List<BigDecimal> getCenteringTimeSec() {
                if (centeringTimeSec == null) {
                    centeringTimeSec = new ArrayList<BigDecimal>();
                }
                return this.centeringTimeSec;
            }

            /**
             * Gets the value of the reference property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the reference property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getReference().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getReference() {
                if (reference == null) {
                    reference = new ArrayList<String>();
                }
                return this.reference;
            }

            /**
             * Gets the value of the centeringFrequency property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the centeringFrequency property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCenteringFrequency().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getCenteringFrequency() {
                if (centeringFrequency == null) {
                    centeringFrequency = new ArrayList<String>();
                }
                return this.centeringFrequency;
            }

            /**
             * Gets the value of the detector property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the detector property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getDetector().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getDetector() {
                if (detector == null) {
                    detector = new ArrayList<String>();
                }
                return this.detector;
            }

            /**
             * Gets the value of the cupSettings property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the cupSettings property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCupSettings().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getCupSettings() {
                if (cupSettings == null) {
                    cupSettings = new ArrayList<String>();
                }
                return this.cupSettings;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="time" type="{http://www.w3.org/2001/XMLSchema}time"/>
         *         &lt;element name="qt1y" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="pbm" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="data">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="peak" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="peak_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="scan" maxOccurs="unbounded">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="scan_number" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
         *                                       &lt;element name="trim_mass" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                                       &lt;element name="time_stamp_sec" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *                                       &lt;element name="autocentering" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="ion_count" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" maxOccurs="unbounded"/>
         *                                       &lt;element name="norm_count" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "date",
            "time",
            "qt1Y",
            "pbm",
            "data"
        })
        public static class Set {

            @XmlElement(required = true)
            @XmlSchemaType(name = "date")
            protected String date;
            @XmlElement(required = true)
            @XmlSchemaType(name = "time")
            protected String time;
            @XmlElement(name = "qt1y")
            protected int qt1Y;
            @XmlElement(required = true)
            protected String pbm;
            @XmlElement(required = true)
            protected PrawnLegacyFile.Run.Set.Data data;

            /**
             * Gets the value of the date property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public String getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDate(String value) {
                this.date = value;
            }

            /**
             * Gets the value of the time property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public String getTime() {
                return time;
            }

            /**
             * Sets the value of the time property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setTime(String value) {
                this.time = value;
            }

            /**
             * Gets the value of the qt1Y property.
             * 
             */
            public int getQt1Y() {
                return qt1Y;
            }

            /**
             * Sets the value of the qt1Y property.
             * 
             */
            public void setQt1Y(int value) {
                this.qt1Y = value;
            }

            /**
             * Gets the value of the pbm property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPbm() {
                return pbm;
            }

            /**
             * Sets the value of the pbm property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPbm(String value) {
                this.pbm = value;
            }

            /**
             * Gets the value of the data property.
             * 
             * @return
             *     possible object is
             *     {@link PrawnFile.Run.Set.Data }
             *     
             */
            public PrawnLegacyFile.Run.Set.Data getData() {
                return data;
            }

            /**
             * Sets the value of the data property.
             * 
             * @param value
             *     allowed object is
             *     {@link PrawnFile.Run.Set.Data }
             *     
             */
            public void setData(PrawnLegacyFile.Run.Set.Data value) {
                this.data = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="peak" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="peak_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="scan" maxOccurs="unbounded">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="scan_number" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
             *                             &lt;element name="trim_mass" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *                             &lt;element name="time_stamp_sec" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
             *                             &lt;element name="autocentering" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="ion_count" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" maxOccurs="unbounded"/>
             *                             &lt;element name="norm_count" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "peak"
            })
            public static class Data {

                @XmlElement(required = true)
                protected List<PrawnLegacyFile.Run.Set.Data.Peak> peak;

                /**
                 * Gets the value of the peak property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the peak property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPeak().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link PrawnFile.Run.Set.Data.Peak }
                 * 
                 * 
                 */
                public List<PrawnLegacyFile.Run.Set.Data.Peak> getPeak() {
                    if (peak == null) {
                        peak = new ArrayList<PrawnLegacyFile.Run.Set.Data.Peak>();
                    }
                    return this.peak;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="peak_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="scan" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="scan_number" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                 *                   &lt;element name="trim_mass" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
                 *                   &lt;element name="time_stamp_sec" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
                 *                   &lt;element name="autocentering" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="ion_count" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" maxOccurs="unbounded"/>
                 *                   &lt;element name="norm_count" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "peakName",
                    "scan"
                })
                public static class Peak {

                    @XmlElement(name = "peak_name", required = true)
                    protected String peakName;
                    @XmlElement(required = true)
                    protected List<PrawnLegacyFile.Run.Set.Data.Peak.Scan> scan;

                    /**
                     * Gets the value of the peakName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getPeakName() {
                        return peakName;
                    }

                    /**
                     * Sets the value of the peakName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setPeakName(String value) {
                        this.peakName = value;
                    }

                    /**
                     * Gets the value of the scan property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the scan property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getScan().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link PrawnFile.Run.Set.Data.Peak.Scan }
                     * 
                     * 
                     */
                    public List<PrawnLegacyFile.Run.Set.Data.Peak.Scan> getScan() {
                        if (scan == null) {
                            scan = new ArrayList<PrawnLegacyFile.Run.Set.Data.Peak.Scan>();
                        }
                        return this.scan;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="scan_number" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/>
                     *         &lt;element name="trim_mass" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
                     *         &lt;element name="time_stamp_sec" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
                     *         &lt;element name="autocentering" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="ion_count" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" maxOccurs="unbounded"/>
                     *         &lt;element name="norm_count" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "scanNumber",
                        "trimMass",
                        "timeStampSec",
                        "autocentering",
                        "ionCount",
                        "normCount"
                    })
                    public static class Scan {

                        @XmlElement(name = "scan_number")
                        @XmlSchemaType(name = "unsignedByte")
                        protected short scanNumber;
                        @XmlElement(name = "trim_mass", required = true)
                        protected BigDecimal trimMass;
                        @XmlElement(name = "time_stamp_sec", required = true)
                        protected BigDecimal timeStampSec;
                        @XmlElement(required = true)
                        protected String autocentering;
                        @XmlElement(name = "ion_count", type = Integer.class)
                        @XmlSchemaType(name = "unsignedInt")
                        protected List<Integer> ionCount;
                        @XmlElement(name = "norm_count", type = Long.class)
                        @XmlSchemaType(name = "unsignedInt")
                        protected List<Long> normCount;

                        /**
                         * Gets the value of the scanNumber property.
                         * 
                         */
                        public short getScanNumber() {
                            return scanNumber;
                        }

                        /**
                         * Sets the value of the scanNumber property.
                         * 
                         */
                        public void setScanNumber(short value) {
                            this.scanNumber = value;
                        }

                        /**
                         * Gets the value of the trimMass property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link BigDecimal }
                         *     
                         */
                        public BigDecimal getTrimMass() {
                            return trimMass;
                        }

                        /**
                         * Sets the value of the trimMass property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link BigDecimal }
                         *     
                         */
                        public void setTrimMass(BigDecimal value) {
                            this.trimMass = value;
                        }

                        /**
                         * Gets the value of the timeStampSec property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link BigDecimal }
                         *     
                         */
                        public BigDecimal getTimeStampSec() {
                            return timeStampSec;
                        }

                        /**
                         * Sets the value of the timeStampSec property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link BigDecimal }
                         *     
                         */
                        public void setTimeStampSec(BigDecimal value) {
                            this.timeStampSec = value;
                        }

                        /**
                         * Gets the value of the autocentering property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAutocentering() {
                            return autocentering;
                        }

                        /**
                         * Sets the value of the autocentering property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAutocentering(String value) {
                            this.autocentering = value;
                        }

                        /**
                         * Gets the value of the ionCount property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the ionCount property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getIonCount().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link Integer }
                         * 
                         * 
                         */
                        public List<Integer> getIonCount() {
                            if (ionCount == null) {
                                ionCount = new ArrayList<Integer>();
                            }
                            return this.ionCount;
                        }

                        /**
                         * Gets the value of the normCount property.
                         * 
                         * <p>
                         * This accessor method returns a reference to the live list,
                         * not a snapshot. Therefore any modification you make to the
                         * returned list will be present inside the JAXB object.
                         * This is why there is not a <CODE>set</CODE> method for the normCount property.
                         * 
                         * <p>
                         * For example, to add a new item, do as follows:
                         * <pre>
                         *    getNormCount().add(newItem);
                         * </pre>
                         * 
                         * 
                         * <p>
                         * Objects of the following type(s) are allowed in the list
                         * {@link Long }
                         * 
                         * 
                         */
                        public List<Long> getNormCount() {
                            if (normCount == null) {
                                normCount = new ArrayList<Long>();
                            }
                            return this.normCount;
                        }

                    }

                }

            }

        }

    }

}
