/*
 * Copyright 2015 CIRDLES.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
 * See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
 * Any modifications to this file will be lost upon recompilation of the source schema. 
 * Generated on: 2015.10.25 at 07:31:08 AM EDT 
 */
package org.cirdles.squid.prawn;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="software_version" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="runs" type="{http://www.w3.org/2001/XMLSchema}unsignedByte"/&gt;
 *         &lt;element name="session_quality" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="session_comments" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="mount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="run" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="par" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}RunParameterNames" /&gt;
 *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="run_table"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="entry" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="par" maxOccurs="unbounded"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}RunTableEntryParameterNames" /&gt;
 *                                               &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="entries" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                           &lt;attribute name="parameters" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                           &lt;attribute name="sample_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="set"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="par" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}SetParameterNames" /&gt;
 *                                     &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="scan" maxOccurs="unbounded"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="measurement" maxOccurs="unbounded"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="par" maxOccurs="unbounded"&gt;
 *                                                   &lt;complexType&gt;
 *                                                     &lt;complexContent&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                         &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}MeasurementParameterNames" /&gt;
 *                                                         &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/complexContent&gt;
 *                                                   &lt;/complexType&gt;
 *                                                 &lt;/element&gt;
 *                                                 &lt;element name="data" maxOccurs="unbounded"&gt;
 *                                                   &lt;complexType&gt;
 *                                                     &lt;simpleContent&gt;
 *                                                       &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *                                                         &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                                                       &lt;/extension&gt;
 *                                                     &lt;/simpleContent&gt;
 *                                                   &lt;/complexType&gt;
 *                                                 &lt;/element&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                     &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "softwareVersion",
    "runs",
    "sessionQuality",
    "sessionComments",
    "mount",
    "run"
})
@XmlRootElement(name = "prawn_file")
public class PrawnFile implements Serializable {

    private static final long serialVersionUID = 8704130590199113402L;

    /**
     *
     */
    @XmlElement(name = "software_version", required = true)
    protected String softwareVersion;

    /**
     *
     */
    @XmlSchemaType(name = "unsignedByte")
    protected short runs;

    /**
     *
     */
    @XmlElement(name = "session_quality", required = true)
    protected String sessionQuality;

    /**
     *
     */
    @XmlElement(name = "session_comments", required = true)
    protected String sessionComments;

    /**
     *
     */
    @XmlElement(required = true)
    protected String mount;

    /**
     *
     */
    @XmlElement(required = true)
    protected List<PrawnFile.Run> run;

    /**
     *
     */
    public PrawnFile() {
        // flag invalid prawnFile
        runs = 0;
    }

    /**
     * Gets the value of the softwareVersion property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSoftwareVersion() {
        return softwareVersion;
    }

    /**
     * Sets the value of the softwareVersion property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSoftwareVersion(String value) {
        this.softwareVersion = value;
    }

    /**
     * Gets the value of the runs property.
     *
     * @return
     */
    public short getRuns() {
        return runs;
    }

    /**
     * Sets the value of the runs property.
     *
     * @param value
     */
    public void setRuns(short value) {
        this.runs = value;
    }

    /**
     * Gets the value of the sessionQuality property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSessionQuality() {
        return sessionQuality;
    }

    /**
     * Sets the value of the sessionQuality property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSessionQuality(String value) {
        this.sessionQuality = value;
    }

    /**
     * Gets the value of the sessionComments property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSessionComments() {
        return sessionComments;
    }

    /**
     * Sets the value of the sessionComments property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSessionComments(String value) {
        this.sessionComments = value;
    }

    /**
     * Gets the value of the mount property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getMount() {
        return mount;
    }

    /**
     * Sets the value of the mount property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setMount(String value) {
        this.mount = value;
    }

    /**
     * Gets the value of the run property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the run property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRun().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PrawnFile.Run }
     *
     *
     * @return
     */
    public List<PrawnFile.Run> getRun() {
        if (run == null) {
            run = new ArrayList<PrawnFile.Run>();
        }
        return this.run;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="par" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}RunParameterNames" /&gt;
     *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="run_table"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="entry" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="par" maxOccurs="unbounded"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}RunTableEntryParameterNames" /&gt;
     *                                     &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="entries" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *                 &lt;attribute name="parameters" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *                 &lt;attribute name="sample_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="set"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="par" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}SetParameterNames" /&gt;
     *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="scan" maxOccurs="unbounded"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="measurement" maxOccurs="unbounded"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="par" maxOccurs="unbounded"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;complexContent&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                               &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}MeasurementParameterNames" /&gt;
     *                                               &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/complexContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                       &lt;element name="data" maxOccurs="unbounded"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;simpleContent&gt;
     *                                             &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
     *                                               &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                                             &lt;/extension&gt;
     *                                           &lt;/simpleContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                           &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "par",
        "runTable",
        "set"
    })
    public static class Run implements Serializable {

        /**
         *
         */
        @XmlElement(required = true)
        protected List<PrawnFile.Run.Par> par;

        /**
         *
         */
        @XmlElement(name = "run_table", required = true)
        protected PrawnFile.Run.RunTable runTable;

        /**
         *
         */
        @XmlElement(required = true)
        protected PrawnFile.Run.Set set;

        /**
         * Gets the value of the par property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the par property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPar().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PrawnFile.Run.Par }
         *
         *
         * @return
         */
        public List<PrawnFile.Run.Par> getPar() {
            if (par == null) {
                par = new ArrayList<>();
            }
            return this.par;
        }

        /**
         * Gets the value of the runTable property.
         *
         * @return possible object is {@link PrawnFile.Run.RunTable }
         *
         */
        public PrawnFile.Run.RunTable getRunTable() {
            return runTable;
        }

        /**
         * Sets the value of the runTable property.
         *
         * @param value allowed object is {@link PrawnFile.Run.RunTable }
         *
         */
        public void setRunTable(PrawnFile.Run.RunTable value) {
            this.runTable = value;
        }

        /**
         * Gets the value of the set property.
         *
         * @return possible object is {@link PrawnFile.Run.Set }
         *
         */
        public PrawnFile.Run.Set getSet() {
            return set;
        }

        /**
         * Sets the value of the set property.
         *
         * @param value allowed object is {@link PrawnFile.Run.Set }
         *
         */
        public void setSet(PrawnFile.Run.Set value) {
            this.set = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}RunParameterNames" /&gt;
         *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Par implements Serializable {

            /**
             *
             */
            @XmlAttribute(name = "name", required = true)
            protected RunParameterNames name;

            /**
             *
             */
            @XmlAttribute(name = "value", required = true)
            protected String value;

            /**
             * Gets the value of the name property.
             *
             * @return possible object is {@link RunParameterNames }
             *
             */
            public RunParameterNames getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value allowed object is {@link RunParameterNames }
             *
             */
            public void setName(RunParameterNames value) {
                this.name = value;
            }

            /**
             * Gets the value of the value property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setValue(String value) {
                this.value = value;
            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="entry" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="par" maxOccurs="unbounded"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}RunTableEntryParameterNames" /&gt;
         *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="entries" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *       &lt;attribute name="parameters" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *       &lt;attribute name="sample_name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "entry"
        })
        public static class RunTable implements Serializable {

            /**
             *
             */
            @XmlElement(required = true)
            protected List<PrawnFile.Run.RunTable.Entry> entry;

            /**
             *
             */
            @XmlAttribute(name = "entries", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short entries;

            /**
             *
             */
            @XmlAttribute(name = "parameters", required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short parameters;

            /**
             *
             */
            @XmlAttribute(name = "sample_name", required = true)
            protected String sampleName;

            /**
             * Gets the value of the entry property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a <CODE>set</CODE> method for the entry property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEntry().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PrawnFile.Run.RunTable.Entry }
             *
             *
             * @return
             */
            public List<PrawnFile.Run.RunTable.Entry> getEntry() {
                if (entry == null) {
                    entry = new ArrayList<>();
                }
                return this.entry;
            }

            /**
             * Gets the value of the entries property.
             *
             * @return
             */
            public short getEntries() {
                return entries;
            }

            /**
             * Sets the value of the entries property.
             *
             * @param value
             */
            public void setEntries(short value) {
                this.entries = value;
            }

            /**
             * Gets the value of the parameters property.
             *
             * @return
             */
            public short getParameters() {
                return parameters;
            }

            /**
             * Sets the value of the parameters property.
             *
             * @param value
             */
            public void setParameters(short value) {
                this.parameters = value;
            }

            /**
             * Gets the value of the sampleName property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getSampleName() {
                return sampleName;
            }

            /**
             * Sets the value of the sampleName property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setSampleName(String value) {
                this.sampleName = value;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             *
             * <p>
             * The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="par" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}RunTableEntryParameterNames" /&gt;
             *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "par"
            })
            public static class Entry implements Serializable {

                /**
                 *
                 */
                @XmlElement(required = true)
                protected List<PrawnFile.Run.RunTable.Entry.Par> par;

                /**
                 * Gets the value of the par property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object. This is
                 * why there is not a <CODE>set</CODE> method for the par
                 * property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getPar().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link PrawnFile.Run.RunTable.Entry.Par }
                 *
                 *
                 * @return
                 */
                public List<PrawnFile.Run.RunTable.Entry.Par> getPar() {
                    if (par == null) {
                        par = new ArrayList<>();
                    }
                    return this.par;
                }

                /**
                 * <p>
                 * Java class for anonymous complex type.
                 *
                 * <p>
                 * The following schema fragment specifies the expected content
                 * contained within this class.
                 *
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}RunTableEntryParameterNames" /&gt;
                 *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "")
                public static class Par implements Serializable {

                    /**
                     *
                     */
                    @XmlAttribute(name = "name", required = true)
                    protected RunTableEntryParameterNames name;

                    /**
                     *
                     */
                    @XmlAttribute(name = "value", required = true)
                    protected String value;

                    /**
                     * Gets the value of the name property.
                     *
                     * @return possible object is
                     *     {@link RunTableEntryParameterNames }
                     *
                     */
                    public RunTableEntryParameterNames getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     *
                     * @param value allowed object is
                     *     {@link RunTableEntryParameterNames }
                     *
                     */
                    public void setName(RunTableEntryParameterNames value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the value property.
                     *
                     * @return possible object is {@link String }
                     *
                     */
                    public String getValue() {
                        return value;
                    }

                    /**
                     * Sets the value of the value property.
                     *
                     * @param value allowed object is {@link String }
                     *
                     */
                    public void setValue(String value) {
                        this.value = value;
                    }

                }

            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="par" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}SetParameterNames" /&gt;
         *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="scan" maxOccurs="unbounded"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="measurement" maxOccurs="unbounded"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="par" maxOccurs="unbounded"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;complexContent&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                     &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}MeasurementParameterNames" /&gt;
         *                                     &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/complexContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                             &lt;element name="data" maxOccurs="unbounded"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;simpleContent&gt;
         *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
         *                                     &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *                                   &lt;/extension&gt;
         *                                 &lt;/simpleContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *                 &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "par",
            "scan"
        })
        public static class Set implements Serializable {

            /**
             *
             */
            @XmlElement(required = true)
            protected List<PrawnFile.Run.Set.Par> par;

            /**
             *
             */
            @XmlElement(required = true)
            protected List<PrawnFile.Run.Set.Scan> scan;

            /**
             * Gets the value of the par property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a <CODE>set</CODE> method for the par property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPar().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PrawnFile.Run.Set.Par }
             *
             *
             * @return
             */
            public List<PrawnFile.Run.Set.Par> getPar() {
                if (par == null) {
                    par = new ArrayList<>();
                }
                return this.par;
            }

            /**
             * Gets the value of the scan property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a <CODE>set</CODE> method for the scan property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getScan().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PrawnFile.Run.Set.Scan }
             *
             *
             * @return
             */
            public List<PrawnFile.Run.Set.Scan> getScan() {
                if (scan == null) {
                    scan = new ArrayList<>();
                }
                return this.scan;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             *
             * <p>
             * The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}SetParameterNames" /&gt;
             *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Par implements Serializable {

                /**
                 *
                 */
                @XmlAttribute(name = "name", required = true)
                protected SetParameterNames name;

                /**
                 *
                 */
                @XmlAttribute(name = "value", required = true)
                protected String value;

                /**
                 * Gets the value of the name property.
                 *
                 * @return possible object is {@link SetParameterNames }
                 *
                 */
                public SetParameterNames getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 *
                 * @param value allowed object is {@link SetParameterNames }
                 *
                 */
                public void setName(SetParameterNames value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the value property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setValue(String value) {
                    this.value = value;
                }

            }

            /**
             * <p>
             * Java class for anonymous complex type.
             *
             * <p>
             * The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="measurement" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="par" maxOccurs="unbounded"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;complexContent&gt;
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                           &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}MeasurementParameterNames" /&gt;
             *                           &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                         &lt;/restriction&gt;
             *                       &lt;/complexContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                   &lt;element name="data" maxOccurs="unbounded"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;simpleContent&gt;
             *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
             *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
             *                         &lt;/extension&gt;
             *                       &lt;/simpleContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *       &lt;attribute name="number" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" /&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "measurement"
            })
            public static class Scan implements Serializable {

                /**
                 *
                 */
                @XmlElement(required = true)
                protected List<PrawnFile.Run.Set.Scan.Measurement> measurement;

                /**
                 *
                 */
                @XmlAttribute(name = "number", required = true)
                @XmlSchemaType(name = "unsignedByte")
                protected short number;

                /**
                 * Gets the value of the measurement property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object. This is
                 * why there is not a <CODE>set</CODE> method for the
                 * measurement property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getMeasurement().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link PrawnFile.Run.Set.Scan.Measurement }
                 *
                 *
                 * @return
                 */
                public List<PrawnFile.Run.Set.Scan.Measurement> getMeasurement() {
                    if (measurement == null) {
                        measurement = new ArrayList<>();
                    }
                    return this.measurement;
                }

                /**
                 * Gets the value of the number property.
                 *
                 * @return
                 */
                public short getNumber() {
                    return number;
                }

                /**
                 * Sets the value of the number property.
                 *
                 * @param value
                 */
                public void setNumber(short value) {
                    this.number = value;
                }

                /**
                 * <p>
                 * Java class for anonymous complex type.
                 *
                 * <p>
                 * The following schema fragment specifies the expected content
                 * contained within this class.
                 *
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="par" maxOccurs="unbounded"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;complexContent&gt;
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                 &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}MeasurementParameterNames" /&gt;
                 *                 &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *               &lt;/restriction&gt;
                 *             &lt;/complexContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *         &lt;element name="data" maxOccurs="unbounded"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;simpleContent&gt;
                 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                 *               &lt;/extension&gt;
                 *             &lt;/simpleContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "par",
                    "data"
                })
                public static class Measurement implements Serializable {

                    /**
                     *
                     */
                    @XmlElement(required = true)
                    protected List<PrawnFile.Run.Set.Scan.Measurement.Par> par;

                    /**
                     *
                     */
                    @XmlElement(required = true)
                    protected List<PrawnFile.Run.Set.Scan.Measurement.Data> data;

                    /**
                     * Gets the value of the par property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live
                     * list, not a snapshot. Therefore any modification you make
                     * to the returned list will be present inside the JAXB
                     * object. This is why there is not a <CODE>set</CODE>
                     * method for the par property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getPar().add(newItem);
                     * </pre>
                     *
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link PrawnFile.Run.Set.Scan.Measurement.Par }
                     *
                     *
                     * @return
                     */
                    public List<PrawnFile.Run.Set.Scan.Measurement.Par> getPar() {
                        if (par == null) {
                            par = new ArrayList<>();
                        }
                        return this.par;
                    }

                    /**
                     * Gets the value of the data property.
                     *
                     * <p>
                     * This accessor method returns a reference to the live
                     * list, not a snapshot. Therefore any modification you make
                     * to the returned list will be present inside the JAXB
                     * object. This is why there is not a <CODE>set</CODE>
                     * method for the data property.
                     *
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getData().add(newItem);
                     * </pre>
                     *
                     *
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link PrawnFile.Run.Set.Scan.Measurement.Data }
                     *
                     *
                     * @return
                     */
                    public List<PrawnFile.Run.Set.Scan.Measurement.Data> getData() {
                        if (data == null) {
                            data = new ArrayList<>();
                        }
                        return this.data;
                    }

                    /**
                     * <p>
                     * Java class for anonymous complex type.
                     *
                     * <p>
                     * The following schema fragment specifies the expected
                     * content contained within this class.
                     *
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;simpleContent&gt;
                     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
                     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *     &lt;/extension&gt;
                     *   &lt;/simpleContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     *
                     *
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "value"
                    })
                    public static class Data implements Serializable {

                        /**
                         *
                         */
                        @XmlValue
                        protected String value;

                        /**
                         *
                         */
                        @XmlAttribute(name = "name", required = true)
                        protected String name;

                        /**
                         * Gets the value of the value property.
                         *
                         * @return possible object is {@link String }
                         *
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         *
                         * @param value allowed object is {@link String }
                         *
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                        /**
                         * Gets the value of the name property.
                         *
                         * @return possible object is {@link String }
                         *
                         */
                        public String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         *
                         * @param value allowed object is {@link String }
                         *
                         */
                        public void setName(String value) {
                            this.name = value;
                        }

                    }

                    /**
                     * <p>
                     * Java class for anonymous complex type.
                     *
                     * <p>
                     * The following schema fragment specifies the expected
                     * content contained within this class.
                     *
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;complexContent&gt;
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *       &lt;attribute name="name" use="required" type="{https://raw.githubusercontent.com}MeasurementParameterNames" /&gt;
                     *       &lt;attribute name="value" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
                     *     &lt;/restriction&gt;
                     *   &lt;/complexContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     *
                     *
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "")
                    public static class Par implements Serializable {

                        /**
                         *
                         */
                        @XmlAttribute(name = "name", required = true)
                        protected String name;

                        /**
                         *
                         */
                        @XmlAttribute(name = "value", required = true)
                        protected String value;

                        /**
                         * Gets the value of the name property.
                         *
                         * @return possible object is {@link String }
                         *
                         */
                        public String getName() {
                            return name;
                        }

                        /**
                         * Sets the value of the name property.
                         *
                         * @param value allowed object is {@link String }
                         *
                         */
                        public void setName(String value) {
                            this.name = value;
                        }

                        /**
                         * Gets the value of the value property.
                         *
                         * @return possible object is {@link String }
                         *
                         */
                        public String getValue() {
                            return value;
                        }

                        /**
                         * Sets the value of the value property.
                         *
                         * @param value allowed object is {@link String }
                         *
                         */
                        public void setValue(String value) {
                            this.value = value;
                        }

                    }

                }

            }

        }

    }

}
